### ISSUE TITLE
[CRITICAL] I cannot have more than ten years on my planner

### ISSUE THREAD

**Issue by jackburkhardt** [dilanx/plan-northwestern#1]
I should be able to have as many years as I want on my planner. 10 is simply not enough and quite honestly is weak sauce. I would like to have at least 50 years so i can become the greatyest computer scientiest to ever live. This is so buggy and I can't believe it is broken. My dissapointment is immesurable and my day is ruined. Please fix!!!!!!!!!!!!!

https://user-images.githubusercontent.com/43016465/145486444-bcfe63d0-d3e6-484f-ad81-ee169442af80.png

**Comment by dilanx** [comment]
Dear github user jackburkhardt do NOT call 10 year max "weak sauce" it is NOT weak sauce ok I will not fix.
