### ISSUE TITLE
Delete and info on course cards overlap with course name

### ISSUE THREAD

**Issue by jared2183** [dilanx/plan-northwestern#11]
instead of having a button for the info and delete on hover which sometimes overlaps with course name and takes up a lot of space can instead have a small minus symbol in the top right (like when you're deleting an app in iOS) that will delete the course and to get info just click on the card (like the whole card is a button - salad nu does this)

**Comment by dilanx** [comment]
I like this idea. I made the change in version 1.1.0. c8cccca466f7d818d7e6a50c5f634d1084007c52
