### ISSUE TITLE
Needs a 5th year option

### ISSUE THREAD

**Issue by GamerBotGH** [dilanx/plan-northwestern#14]
Hi! I think this could use an option to add a 5th year. There's a fair amount of people who are dual degree or do the 5-year Bachelors/Masters program or have other reasons to do college in 5 years instead of 4.

*This feedback was shared using the external feedback form and was automatically posted here.*

**Comment by dilanx** [comment]
This feature has existed since launch. Press the "Add Year" button at the top left of the screen to add up to a total of 10 years.

**Comment by dilanx** [comment]
I'll move the button lol #19
