### ISSUE TITLE
Minimize Year

### ISSUE THREAD

**Issue by sky-larke** [dilanx/plan-northwestern#15]
Salutations, Github User dilanx,

Whilst regarding my projected classes for next year, I have come across the conundrum of being unable to view only one year at a time. This is not pog, Github User dilanx. I would like to be able to minimize a year so I can pretend that EA never happened. Please add this feature posthaste. 

ty

**Comment by dilanx** [comment]
I like the idea. I've added this in version 1.1.0. c8cccca466f7d818d7e6a50c5f634d1084007c52
