### ISSUE TITLE
Include if classes fill Weinberg distros

### ISSUE THREAD

**Issue by GamerBotGH** [dilanx/plan-northwestern#8]
First, thank you so much for making this. I've spent way too much time researching what classes to take to complete both my Learning Sciences and CS majors (especially because SESP isn't that transparent about their requirements). It would be great if you could include if the classes fulfill Weinberg distros, since it's a big factor in what classes people choose to take. The list of courses are listed here by year (they're also on CAESAR): https://weinberg.northwestern.edu/undergraduate/degree/distribution-requirements/approved-courses.html

*This feedback was shared using the external feedback form and was automatically posted here.*

**Comment by dilanx** [comment]
You can already see Weinberg distro info for each course, but if you meant that you want to have an indicator of the total number of fulfilled units for each area, I might be able to add something like that. Check out #9 for that.
